// paradox-modding-tool/frontend/src/pages/ModdingDocs.vue
<template>
  <div class="p-2 flex-1 flex flex-col min-h-0">
    <Tabs v-model:value="activeTab">
      <TabList>
        <Tab value="0">Script docs</Tab>
        <Tab value="1">Modding wiki</Tab>
      </TabList>

      <TabPanels>
        <TabPanel value="0">
          <Card :pt="toolbarCardPt">
            <template #content>
              <div class="flex flex-wrap items-end gap-4">
                <div class="min-w-200">
                  <label>Game install path</label>
                  <InputText v-model="installPathDisplay" readonly placeholder="Set in Settings (gear icon in header)"
                    class="w-full" />
                </div>
                <Button label="Scan" icon="pi pi-refresh" :loading="scanning" :disabled="!installPathDisplay"
                  @click="scan" />
              </div>
            </template>
          </Card>
          <Message v-if="scanError" severity="error" :closable="true" @close="scanError = ''">
            {{ scanError }}
          </Message>
          <Card :pt="editorCardPt">
            <template #content>
              <div class="flex flex-1 min-h-0 overflow-hidden rounded-lg border border-(--p-surface-800)">
                <div class="flex-1 min-w-0 min-h-0 flex flex-col overflow-hidden rounded-l pr-1">
                  <InputText v-model="filterText" placeholder="Filter by filename"
                    class="w-full mb-1 py-1 px-2 text-[13px]" aria-label="Filter by filename" />
                  <div class="flex-1 min-h-0 overflow-auto">
                    <TreeTable v-model:selectionKeys="selectionKeys" v-model:expandedKeys="expandedKeys"
                      :value="docTreeNodes" selectionMode="single" :metaKeySelection="false" dataKey="key" scrollable
                      scrollHeight="flex" @node-select="onNodeSelect" class="w-full">
                      <template #empty>No files match.</template>
                      <Column field="name" header="File" expander />
                    </TreeTable>
                  </div>
                </div>
                <div class="flex-1 min-w-0 min-h-0 flex flex-col overflow-hidden rounded-r -ml-px">
                  <CodeViewer v-if="fileContent !== null" :content="fileContent"
                    :filename="selectedEntry?.relativePath ?? 'Select a file'" />
                  <p v-else class="p-4 text-slate-400 bg-dark-input">Select a file to view content.</p>
                </div>
              </div>
            </template>
          </Card>
        </TabPanel>
        <TabPanel value="1">
          <iframe v-if="wikiUrl" :src="wikiUrl" :title="'Modding Wiki'" class="flex-1 min-h-0" />
        </TabPanel>
      </TabPanels>
    </Tabs>
  </div>
</template>

<script setup>
import { ref, computed, watch, nextTick } from 'vue'
import { useAppSettings } from '../composables/useAppSettings'
import { buildDocTree } from '../utils/docTree.js'
import {
  ListGameDocFiles,
  ReadFileContent,
  GetScriptRoot
} from '../../bindings/paradox-modding-tool/fileservice.js'
import {
  GetDocPathCache,
  SetDocPathCache,
  ClearDocPathCache
} from '../../bindings/paradox-modding-tool/settingsservice.js'
import CodeViewer from '../components/CodeViewer.vue'

const { game, gameInstallPath } = useAppSettings()

const activeTab = ref('0')

const installPathDisplay = computed(() => gameInstallPath.value)

const docEntries = ref([])
const filterText = ref('')
const selectionKeys = ref(null)
const expandedKeys = ref({})
const selectedEntry = ref(null)
const fileContent = ref(null)
const scanning = ref(false)
const scanError = ref('')

const filteredEntries = computed(() => {
  const text = (filterText.value || '').trim().toLowerCase()
  if (!text) return docEntries.value
  return docEntries.value.filter((e) =>
    (e.relativePath || '').toLowerCase().includes(text)
  )
})

const docTreeNodes = computed(() => buildDocTree(filteredEntries.value))

const wikiUrl = computed(() =>
  game.value === 'eu5'
    ? 'https://eu5.paradoxwikis.com/Modding'
    : 'https://ck3.paradoxwikis.com/Modding'
)

const toolbarCardPt = {
  content: { class: 'py-2 px-3' }
}

const editorCardPt = {
  root: { class: 'flex-1 min-h-0 flex flex-col overflow-hidden' },
  body: { class: 'flex-1 min-h-0 overflow-hidden flex flex-col' },
  content: { class: 'flex-1 min-h-0 overflow-hidden flex flex-col' }
}

/** Load file list from cache for current game+path only. No scan. If no cache, show empty. */
async function loadFromCache() {
  const path = gameInstallPath.value?.trim()
  filterText.value = ''
  expandedKeys.value = {}
  selectionKeys.value = {}
  selectedEntry.value = null
  fileContent.value = null
  if (!path) {
    docEntries.value = []
    scanError.value = ''
    return
  }
  try {
    const cached = await GetDocPathCache(game.value, path).catch(() => null)
    if (cached?.paths?.length) {
      docEntries.value = cached.paths.map((relativePath) => ({ relativePath, fullPath: '' }))
      scanError.value = ''
    } else {
      docEntries.value = []
      scanError.value = ''
    }
  } catch {
    docEntries.value = []
    scanError.value = ''
  }
}

async function scan() {
  const path = gameInstallPath.value?.trim()
  if (!path) {
    scanError.value = 'Select game install path first.'
    return
  }
  scanning.value = true
  scanError.value = ''
  try {
    const list = await ListGameDocFiles(game.value, path)
    docEntries.value = list ?? []
    await SetDocPathCache(game.value, path, {
      paths: docEntries.value.map((e) => e.relativePath),
      scannedAt: new Date().toISOString(),
    })
  } catch (e) {
    scanError.value = e?.message ?? String(e)
    docEntries.value = []
  } finally {
    scanning.value = false
  }
}

function onNodeSelect(node) {
  // Folder: toggle expand/collapse, don't select or load file
  if (node.children?.length) {
    const key = node.key
    const next = { ...expandedKeys.value }
    next[key] = !next[key]
    expandedKeys.value = next
    nextTick(() => {
      selectionKeys.value = {}
    })
    return
  }

  if (!node?.data?.relativePath) {
    selectionKeys.value = {}
    selectedEntry.value = null
    fileContent.value = null
    return
  }
  selectedEntry.value = { relativePath: node.data.relativePath, fullPath: '' }
  loadFileForEntry(selectedEntry.value)
}

async function loadFileForEntry(entry) {
  if (!entry?.relativePath) {
    fileContent.value = null
    return
  }
  let fullPath = entry.fullPath
  if (!fullPath && gameInstallPath.value?.trim()) {
    try {
      const root = await GetScriptRoot(gameInstallPath.value, game.value)
      fullPath = root.replace(/\\/g, '/') + '/' + entry.relativePath
    } catch {
      fullPath = ''
    }
  }
  if (!fullPath?.trim()) {
    fileContent.value = null
    return
  }
  fileContent.value = null
  try {
    const content = await ReadFileContent(fullPath)
    fileContent.value = content ?? ''
  } catch {
    fileContent.value = ''
  }
}

watch([game, gameInstallPath], () => {
  loadFromCache()
}, { immediate: true })
</script>

// frontend/src/lib/pages/ModdingDocs.svelte
<script lang="ts">
  import { Tab, Tabs, Card, CardBody, FileTree, EditorPane, SplitPane } from "@components";
  import Icon from "@iconify/svelte";
  import { game, gameInstallPath, appConstants } from "@stores/app.svelte";
  import { Scan, GetDocPathCache, GetDocContent } from "@services/moddocservice";
  import { OpenURL } from "@services/browserservice";
  import { BuildTree } from "@services/fileservice";
  import type { TreeNode } from "@services/models";

  let filterText = $state("");
  let docFiles = $state<string[]>([]);
  let docTree = $state<TreeNode[]>([]);
  let selectedEntry = $state<{ name: string; content: string }>();

  $effect(() => {
    const g = $game;
    const path = $gameInstallPath;
    GetDocPathCache(g, path).then(async (cache) => {
      if (cache) {
        docFiles = cache.paths;
        docTree = await BuildTree(docFiles);
      } else {
        docFiles = [];
        docTree = [];
      }
    });
  });

  async function scan() {
    try {
      docFiles = await Scan($game, $gameInstallPath);
      docTree = await BuildTree(docFiles);
    } catch (error) {
      console.error(error);
    }
  }

  async function onFileClick(file: TreeNode) {
    const content = await GetDocContent($game, $gameInstallPath, file.relPath);
    selectedEntry = {
      name: file.name,
      content: content ?? "",
    };
  }

  const wikiUrl = $derived($game === "CK3" ? $appConstants.ck3.wikiUrl : $appConstants.eu5.wikiUrl);
</script>

<div class="relative p-4 max-w-full min-w-0">
  <Tabs class="tabs-border tabs-xl">
    <Tab
      tabGroup="modding-docs"
      label="Script docs"
      selected
      contentClass="flex flex-col min-h-0 bg-base-200/50 border-base-content/10 h-[calc(93.5vh-6rem)]"
      ><Card>
        <CardBody>
          <fieldset class="fieldset">
            <legend class="fieldset-legend text-base-content/90">Game install path:</legend>
            <div class="flex gap-2">
              <input
                type="text"
                class="input flex-1 min-w-0"
                readonly
                value={$gameInstallPath}
                placeholder="Set in Settings (gear icon in header)"
              />
              <button type="button" class="btn btn-soft btn-accent" disabled={!$gameInstallPath?.trim()} onclick={scan}>
                Scan
              </button>
            </div>
          </fieldset>
        </CardBody>
      </Card>
      <Card class="flex-1 min-h-0 min-w-0 flex flex-col">
        <CardBody class="flex-1 min-h-0 min-w-0 flex flex-col overflow-hidden p-2">
          <SplitPane fixedSide="first" class="flex-1 min-h-0">
            {#snippet first()}
              <div class="flex flex-col h-full overflow-hidden bg-base-200">
                <div
                  class="flex h-22 shrink-0 flex-col justify-center px-3 py-2 bg-base-200/50 border-b border-base-content/10"
                >
                  <label class="label py-1" for="file-filter-input">
                    <span class="label-text font-semibold text-sm">Filter Files</span>
                  </label>
                  <div class="relative">
                    <input
                      id="file-filter-input"
                      type="text"
                      class="input input-bordered w-full bg-base-100 focus:bg-base-100"
                      bind:value={filterText}
                      placeholder="Type to filter by filename..."
                    />
                    {#if filterText}
                      <button
                        type="button"
                        class="absolute right-2 top-1/2 -translate-y-1/2 btn btn-ghost btn-xs btn-circle"
                        onclick={() => (filterText = "")}
                        title="Clear filter"
                      >
                        ✕
                      </button>
                    {/if}
                  </div>
                </div>
                <div class="flex-1 min-h-0 overflow-auto p-2">
                  <FileTree tree={docTree} filter={filterText} fileColor="text-accent" {onFileClick} />
                </div>
              </div>
            {/snippet}
            {#snippet second()}
              <div class="flex flex-col h-full overflow-hidden bg-dark-input shadow-inner">
                <div
                  class="flex h-8 shrink-0 items-center px-3 bg-base-200/50 border-b border-base-content/10 text-sm font-bold text-base-content/60"
                >
                  File Content
                </div>
                <EditorPane
                  content={selectedEntry?.content ?? ""}
                  filename={selectedEntry?.name ?? "Select a file"}
                  placeholder="Select a file to view content"
                />
              </div>
            {/snippet}
          </SplitPane>
        </CardBody>
      </Card>
    </Tab>
    <Tab
      tabGroup="modding-docs"
      label="Modding Wiki"
      contentClass="bg-base-200/50 border-base-content/10 p-2 h-[calc(93.5vh-6rem)]"
    >
      <div class="flex flex-col gap-2 h-full">
        <div class="flex justify-end shrink-0">
          <button type="button" class="btn btn-sm btn-secondary btn-outline" onclick={() => OpenURL(wikiUrl)}>
            <Icon icon="mdi:open-in-new" class="size-4" />
            Open in Browser
          </button>
        </div>
        <iframe src={wikiUrl} title="Modding Wiki" class="w-full flex-1 min-h-0"></iframe>
      </div>
    </Tab>
  </Tabs>
</div>
