// paradox-modding-tools/frontend/src/lib/pages/Settings.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Card, CardBody } from "../components";
  import { SelectDirectory } from "../../../bindings/paradox-modding-tools/services/fileservice";
  import {
    goBack,
    gameInstallPathCk3,
    gameInstallPathEu5,
    saveSettings,
    loadSettings,
  } from "../stores/app";

  onMount(() => {
    loadSettings();
  });

  async function save() {
    await saveSettings();
  }

  async function browseGameDirectory(game: "CK3" | "EU5") {
    const path = await SelectDirectory(`Select ${game} game directory`);
    if (path) {
      if (game === "CK3") {
        gameInstallPathCk3.set(path);
      } else {
        gameInstallPathEu5.set(path);
      }
    }
  }
</script>

<div class="p-4">
  <div class="max-w-3xl mx-auto w-full">
    <button
      type="button"
      class="btn btn-ghost btn-md gap-2 mb-2 -ml-2 text-base-content/80 hover:text-base-content"
      onclick={goBack}
    >
      ← Back
    </button>
    <h2 class="text-center text-xl font-semibold mb-4 text-base-content/90">
      Settings
    </h2>
    <Card class="bg-base-300 border border-base-content/10">
      <CardBody class="p-6">
        <h3 class="card-title text-base-content/90 mb-2">
          Game install directories
        </h3>
        <p class="text-sm text-base-content/80 mb-4">
          Set the (top-level) install path for each game. These are used by
          Modding Docs, Compare (vanilla vs mod), and Merge (vanilla vs mod).
        </p>
        <div class="flex flex-col gap-4">
          <fieldset class="fieldset">
            <legend class="fieldset-legend text-base-content/90">
              Crusader Kings III (CK3)
            </legend>
            <div class="join">
              <button
                type="button"
                class="btn btn-primary join-item"
                onclick={() => browseGameDirectory("CK3")}
              >
                Browse
              </button>
              <input
                type="text"
                class="input join-item flex-1"
                readonly
                value={$gameInstallPathCk3}
                placeholder="Select CK3 game directory"
              />
            </div>
            <p class="label">
              Steam example: <code
                >C:\Program Files (x86)\Steam\steamapps\common\Crusader Kings
                III</code
              >
            </p>
          </fieldset>
          <fieldset class="fieldset">
            <legend class="fieldset-legend text-base-content/90">
              Europa Universalis V (EU5)
            </legend>
            <div class="join">
              <button
                type="button"
                class="btn btn-primary join-item"
                onclick={() => browseGameDirectory("EU5")}
              >
                Browse
              </button>
              <input
                type="text"
                class="input join-item flex-1"
                readonly
                value={$gameInstallPathEu5}
                placeholder="Select EU5 game directory"
              />
            </div>
            <p class="label">
              Steam example: <code
                >C:\Program Files (x86)\Steam\steamapps\common\Europa
                Universalis V</code
              >
            </p>
          </fieldset>
        </div>
        <div
          class="card-actions justify-end mt-6 pt-4 border-t border-base-content/10"
        >
          <!-- TODO: Add Toast notification for success/error after save -->
          <button type="button" class="btn btn-primary" onclick={save}>
            Save Settings
          </button>
        </div>
      </CardBody>
    </Card>
  </div>
</div>

// OLD-paradox-modding-tool/frontend/src/pages/Settings.vue
<template>
  <div class="flex-1 flex flex-col min-h-0 min-w-0 p-4 overflow-auto">
    <div class="max-w-2xl mx-auto w-full pt-6">
      <h2 class="text-xl font-semibold mb-4">Settings</h2>
      <Card class="mb-4">
        <template #title>Game install directories</template>
        <template #content>
          <p class="text-(--p-surface-600) dark:text-(--p-surface-400) text-sm mb-4">
            Set the install path for each game. These are used by Modding Docs, Compare (vanilla vs mod), and Merge
            (vanilla vs mod).
          </p>
          <div class="flex flex-col gap-4">
            <div class="flex flex-col gap-2">
              <label class="text-sm font-medium">Crusader Kings III (CK3)</label>
              <div class="flex gap-2">
                <InputText :model-value="gameInstallPathCk3" readonly class="flex-1"
                  placeholder="Select CK3 install directory" />
                <Button label="Browse" icon="pi pi-folder-open" @click="browseCk3" />
              </div>
            </div>
            <div class="flex flex-col gap-2">
              <label class="text-sm font-medium">Europa Universalis V (EU5)</label>
              <div class="flex gap-2">
                <InputText :model-value="gameInstallPathEu5" readonly class="flex-1"
                  placeholder="Select EU5 install directory" />
                <Button label="Browse" icon="pi pi-folder-open" @click="browseEu5" />
              </div>
            </div>
          </div>
        </template>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { useAppSettings } from '../composables/useAppSettings'
import { SelectDirectory } from '../../bindings/paradox-modding-tool/fileservice.js'

const {
  game,
  gameInstallPathCk3,
  gameInstallPathEu5,
  setGame,
  setGameInstallPathCk3,
  setGameInstallPathEu5
} = useAppSettings()

const gameOptions = [
  { label: 'CK3', value: 'ck3' },
  { label: 'EU5', value: 'eu5' }
]

async function browseCk3() {
  try {
    const path = await SelectDirectory('Select Crusader Kings III install directory')
    if (path) await setGameInstallPathCk3(path)
  } catch (e) {
    alert('Error selecting directory: ' + (e?.message ?? e))
  }
}

async function browseEu5() {
  try {
    const path = await SelectDirectory('Select Europa Universalis V install directory')
    if (path) await setGameInstallPathEu5(path)
  } catch (e) {
    alert('Error selecting directory: ' + (e?.message ?? e))
  }
}
</script>
