// paradox-modding-tool/frontend/src/components/FileSelector.vue
<template>
  <div>
    <label v-if="label" class="block mb-2 font-medium text-sm">{{ label }}</label>
    <p v-if="hint" class="text-xs text-gray-500 mb-1">{{ hint }}</p>
    <Textarea :modelValue="modelValue.join('\n')" @update:modelValue="updatePaths" rows="3" :placeholder="placeholder"
      class="w-full min-w-0 px-3 py-2" />
    <div class="flex flex-wrap gap-2 mt-2">
      <Button :label="fileButtonLabel" @click="selectFiles" size="small" />
      <Button :label="folderButtonLabel" @click="selectFolder" size="small" />
      <Button label="Clear" severity="secondary" @click="clear" size="small" />
    </div>
    <span v-if="modelValue.length" class="text-sm text-gray-400 mt-1 block">
      {{ modelValue.length }} {{ modelValue.length === 1 ? 'item' : 'items' }}
    </span>
  </div>
</template>

<script setup>
import { SelectDirectory, SelectMultipleFiles } from '../../bindings/paradox-modding-tool/fileservice.js'
import Button from 'primevue/button'
import Textarea from 'primevue/textarea'
import { parsePathList } from '../utils/paths.js'

const props = defineProps({
  modelValue: {
    type: Array,
    default: () => []
  },
  label: {
    type: String,
    default: 'Files / Folders:'
  },
  placeholder: {
    type: String,
    default: 'Select files or directories...'
  },
  fileDialogTitle: {
    type: String,
    default: 'Select Files to Scan'
  },
  folderDialogTitle: {
    type: String,
    default: 'Select Folder to Scan'
  },
  fileFilter: {
    type: String,
    default: '*.txt; *.json'
  },
  fileButtonLabel: {
    type: String,
    default: 'Select File(s)'
  },
  folderButtonLabel: {
    type: String,
    default: 'Select Folder'
  },
  hint: {
    type: String,
    default: ''
  }
})

const emit = defineEmits(['update:modelValue'])

function updatePaths(value) {
  emit('update:modelValue', parsePathList(value))
}

async function selectFiles() {
  try {
    const selected = await SelectMultipleFiles(props.fileDialogTitle, props.fileFilter)
    if (selected?.length) {
      const existing = new Set(props.modelValue)
      const next = [...props.modelValue]
      for (const p of selected) {
        if (!existing.has(p)) next.push(p)
      }
      emit('update:modelValue', next)
    }
  } catch (e) {
    alert('Error selecting files: ' + e)
  }
}

async function selectFolder() {
  try {
    const selected = await SelectDirectory(props.folderDialogTitle)
    if (selected) {
      const existing = new Set(props.modelValue)
      if (!existing.has(selected)) {
        emit('update:modelValue', [...props.modelValue, selected])
      }
    }
  } catch (e) {
    alert('Error selecting folder: ' + e)
  }
}

function clear() {
  emit('update:modelValue', [])
}
</script>

// paradox-modding-tools/frontend/src/lib/components/wrappers/FileSelector.svelte
<script lang="ts">
  import Icon from "@iconify/svelte";
  import {
    SelectFiles,
    SelectDirectories,
    SelectSingleFile,
    SelectDirectory,
  } from "@services/fileservice";

  let {
    legend = "File Legend:",
    mode = "filesAndFolders",
    placeholder = "Select Files or Folders...",
    dialogTitle = "Select Files or Folders...",
    fileBtnText = "Select File(s)",
    folderBtnText = "Select Folder(s)",
    fileFilter = "*.txt; *.json",
    underHint = "",
    initialValue = [],
    onPathsChange,
  }: {
    legend?: string;
    mode?: "filesAndFolders" | "fileOnly" | "folderOnly";
    placeholder?: string;
    dialogTitle?: string;
    fileBtnText?: string;
    folderBtnText?: string;
    fileFilter?: string;
    underHint?: string;
    initialValue?: string[];
    onPathsChange?: (paths: string[]) => void;
  } = $props();

  let selectedPaths = $state<string[]>([]);

  $effect(() => {
    if (initialValue.length > 0) {
      selectedPaths = [...initialValue];
    }
  });

  async function selectFiles() {
    selectedPaths = selectedPaths.concat(
      await SelectFiles(dialogTitle, fileFilter),
    );
    onPathsChange?.(selectedPaths);
  }

  async function selectSingleFile() {
    selectedPaths[0] = await SelectSingleFile(dialogTitle, fileFilter);
    onPathsChange?.(selectedPaths);
  }

  async function selectDirectories() {
    selectedPaths = selectedPaths.concat(await SelectDirectories(dialogTitle));
    onPathsChange?.(selectedPaths);
  }

  async function selectSingleDirectory() {
    selectedPaths[0] = await SelectDirectory(dialogTitle);
    onPathsChange?.(selectedPaths);
  }

  function clear() {
    selectedPaths = [];
    onPathsChange?.(selectedPaths);
  }
</script>

<fieldset class="fieldset">
  <legend class="fieldset-legend text-base-content/90">{legend}</legend>
  {#if mode === "filesAndFolders"}
    <textarea
      class="textarea w-full max-w-2xl"
      readonly
      value={selectedPaths.join("\n")}
      {placeholder}
    ></textarea>
    <div class="flex flex-wrap gap-2 max-w-2xl w-full">
      <button
        type="button"
        class="btn btn-soft btn-secondary w-39"
        onclick={selectFiles}
      >
        {fileBtnText}
      </button>
      <button
        type="button"
        class="btn btn-soft btn-secondary w-39"
        onclick={selectDirectories}
      >
        {folderBtnText}
      </button>
      <button type="button" class="btn w-25 ml-auto" onclick={clear}>
        Clear
        <Icon icon="mdi:trash-can" class="size-4" />
      </button>
    </div>
    {#if underHint !== ""}
      <p class="label">{underHint}</p>
    {/if}
  {:else if mode === "fileOnly"}
    <div class="join">
      <button
        type="button"
        class="btn btn-soft btn-primary join-item"
        onclick={selectSingleFile}
      >
        {fileBtnText}
      </button>
      <input
        type="text"
        class="input join-item flex-1"
        readonly
        value={selectedPaths[0]}
        {placeholder}
      />
    </div>
    {#if underHint !== ""}
      <p class="label">{underHint}</p>
    {/if}
  {:else if mode === "folderOnly"}
    <div class="join">
      <button
        type="button"
        class="btn btn-soft btn-primary join-item"
        onclick={selectSingleDirectory}
      >
        {folderBtnText}
      </button>
      <input
        type="text"
        class="input join-item flex-1"
        readonly
        value={selectedPaths[0]}
        {placeholder}
      />
    </div>
    {#if underHint !== ""}
      <p class="label">{underHint}</p>
    {/if}
  {/if}
</fieldset>
